config/routes.rb
Rails.application.routes.draw do
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_one :detail, dependent: :destroy, class_name: ItemDetail
  accepts_nested_attributes_for :detail
end

app/models/item_detail.rb
class ItemDetail < ActiveRecord::Base
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.build_detail
  end

  # GET /items/1/edit
  def edit
    @item.build_detail unless @item.detail.present?
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, detail_attributes: %i[id description])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :price
    %br/
    = f.number_field :price

  = f.fields_for :detail do |detail|
    = detail.label :description
    %br/
    = detail.text_field :description

  .actions
    = f.submit

app/views/items/edit.html.haml
%h1 Editing Item
= render 'form'
= link_to 'Show', @item
|
= link_to 'Back', items_path

app/views/items/index.html.haml
%p#notice= notice
%h1 Listing Items
%table
  %thead
    %tr
      %th Name
      %th Price
      %th{:colspan => "3"}
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.price
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New Item
= render 'form'
= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @item.name
%p
  %strong Price:
  = @item.price
%p
  %strong Detail:
  - if @item.detail.present?
    = @item.detail.description

= link_to 'Edit', edit_item_path(@item)
|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RelationFormSample2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield